<div class="row">
    <div class="col-6">
        <div class="row">
            <div class="card col-4">
                <h1>UNOS</h1>
            </div>
            <div class="col-4">
                <h3>Hola</h3>
            </div>
            <div class="card col-4">
                <h3>Hola</h3>
            </div>
        </div>
    </div>
    <div class="col-10">
        <div class="row">
            <div class="col-4">
                <br></br>
            </div>
        </div>
    </div>

    <div class="col-10">
        <div style={{marginLeft:'40px'}} class="row">
            <div style={{marginLeft:'40px'}}  class="card col-4">
                <h1>UNO</h1>
            </div>
            <div style={{marginLeft:'40px'}}     class="card col-4">
                <h3>Holafdsfdfd</h3>
            </div>
        </div>
    </div>
</div> 



{/* <Card className='espaciado-total' style={{background:"lightgreen", width: '25rem' }}>
        <Card.Body>
            <Card.Title>fdfdfd</Card.Title>
            <Card.Img variant="top" src={img} />
            <Card.Text>
                Agencia
            </Card.Text>
        </Card.Body>
        <ListGroup className="list-group-flush">
            <ListGroup.Item>Cras justo odio</ListGroup.Item>
            <ListGroup.Item>Dapibus ac facilisis in</ListGroup.Item>
            <ListGroup.Item>Vestibulum at eros</ListGroup.Item>
        </ListGroup>
        <Card.Body>
            <Card.Link href="#">Card Link</Card.Link>
            <Card.Link href="#">Another Link</Card.Link>
        </Card.Body>
    </Card>
*/}