version: '3'

services:
 backend:
    image: '7771512001/mia-vacas-back-2022'
    container_name: 'backend-node'
    environment:
      PORT: "5000"
      COGNITO_USER_POOL_ID: "us-east-2_279qxbr84"
      COGNITO_CLIENT_ID: "7jrsta5q30hitnh9em1qsiu6kh"
      COGNITO_REGION: "us-east-2"

      ACCESS_KEY_COG: 'AKIAWDWRDMZ5IFTWNN62'
      SECRET_ACCESS_KEY_COG: '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'


      AWS_PUBLIC_KEY: 'AKIAR43GITLBPOACYKXY'
      AWS_SECRET_KEY: '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'
      AWS_BUCKET_NAME: 'web-mia-vacas'
      AWS_BUCKET_REGION: 'us-east-1'
    ports:
      - '5000:5000' #del no de hub al mio
    restart: always